# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: quay.io/prometheus/memcached-exporter
  tag: v0.5.0
  pullPolicy: IfNotPresent

nameOverride: "memcached-exporter"
fullnameOverride: "memcached-exporter"

# the host:port of one of the memcached servers in your cluster
memcached:
  server: ""

service:
  namespace: default
  type: ClusterIP
  port: 9150

serviceMonitor:
  enabled: true
  namespace: monitoring
  annotations: {}
  # Add whatever label the Prometheus service is looking for so this
  # ServiceMonitor will be automatically picked up.
  labels: 
    release: mon
  interval: 30s
  path: /metrics

resources: {}
